# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jordan/Downloads/clion-2017.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/jordan/Downloads/clion-2017.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jordan/projects/Roy-the-Traffic-Cop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jordan/projects/Roy-the-Traffic-Cop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/jordan/Downloads/clion-2017.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/jordan/Downloads/clion-2017.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordan/projects/Roy-the-Traffic-Cop/CMakeFiles /home/jordan/projects/Roy-the-Traffic-Cop/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordan/projects/Roy-the-Traffic-Cop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Roy_the_Traffic_Cop

# Build rule for target.
Roy_the_Traffic_Cop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Roy_the_Traffic_Cop
.PHONY : Roy_the_Traffic_Cop

# fast build rule for target.
Roy_the_Traffic_Cop/fast:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/build
.PHONY : Roy_the_Traffic_Cop/fast

src/Roy-the-Traffic-Cop.o: src/Roy-the-Traffic-Cop.cpp.o

.PHONY : src/Roy-the-Traffic-Cop.o

# target to build an object file
src/Roy-the-Traffic-Cop.cpp.o:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/Roy-the-Traffic-Cop.cpp.o
.PHONY : src/Roy-the-Traffic-Cop.cpp.o

src/Roy-the-Traffic-Cop.i: src/Roy-the-Traffic-Cop.cpp.i

.PHONY : src/Roy-the-Traffic-Cop.i

# target to preprocess a source file
src/Roy-the-Traffic-Cop.cpp.i:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/Roy-the-Traffic-Cop.cpp.i
.PHONY : src/Roy-the-Traffic-Cop.cpp.i

src/Roy-the-Traffic-Cop.s: src/Roy-the-Traffic-Cop.cpp.s

.PHONY : src/Roy-the-Traffic-Cop.s

# target to generate assembly for a file
src/Roy-the-Traffic-Cop.cpp.s:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/Roy-the-Traffic-Cop.cpp.s
.PHONY : src/Roy-the-Traffic-Cop.cpp.s

src/car.o: src/car.cpp.o

.PHONY : src/car.o

# target to build an object file
src/car.cpp.o:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/car.cpp.o
.PHONY : src/car.cpp.o

src/car.i: src/car.cpp.i

.PHONY : src/car.i

# target to preprocess a source file
src/car.cpp.i:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/car.cpp.i
.PHONY : src/car.cpp.i

src/car.s: src/car.cpp.s

.PHONY : src/car.s

# target to generate assembly for a file
src/car.cpp.s:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/car.cpp.s
.PHONY : src/car.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/lane.o: src/lane.cpp.o

.PHONY : src/lane.o

# target to build an object file
src/lane.cpp.o:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/lane.cpp.o
.PHONY : src/lane.cpp.o

src/lane.i: src/lane.cpp.i

.PHONY : src/lane.i

# target to preprocess a source file
src/lane.cpp.i:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/lane.cpp.i
.PHONY : src/lane.cpp.i

src/lane.s: src/lane.cpp.s

.PHONY : src/lane.s

# target to generate assembly for a file
src/lane.cpp.s:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/lane.cpp.s
.PHONY : src/lane.cpp.s

src/traffic_cop.o: src/traffic_cop.cpp.o

.PHONY : src/traffic_cop.o

# target to build an object file
src/traffic_cop.cpp.o:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/traffic_cop.cpp.o
.PHONY : src/traffic_cop.cpp.o

src/traffic_cop.i: src/traffic_cop.cpp.i

.PHONY : src/traffic_cop.i

# target to preprocess a source file
src/traffic_cop.cpp.i:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/traffic_cop.cpp.i
.PHONY : src/traffic_cop.cpp.i

src/traffic_cop.s: src/traffic_cop.cpp.s

.PHONY : src/traffic_cop.s

# target to generate assembly for a file
src/traffic_cop.cpp.s:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/traffic_cop.cpp.s
.PHONY : src/traffic_cop.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/Roy_the_Traffic_Cop.dir/build.make CMakeFiles/Roy_the_Traffic_Cop.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Roy_the_Traffic_Cop"
	@echo "... src/Roy-the-Traffic-Cop.o"
	@echo "... src/Roy-the-Traffic-Cop.i"
	@echo "... src/Roy-the-Traffic-Cop.s"
	@echo "... src/car.o"
	@echo "... src/car.i"
	@echo "... src/car.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/lane.o"
	@echo "... src/lane.i"
	@echo "... src/lane.s"
	@echo "... src/traffic_cop.o"
	@echo "... src/traffic_cop.i"
	@echo "... src/traffic_cop.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

